### ISSUE TITLE
CSI Driver documentation needs to be fixed

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi-driver#48]
I installed the CSI. This is the list of points I have:
1. You need to mention the installation of docker as it is needed for image creation (make build-image)
yum install docker
systemctl start docker

Maybe you can provide a full image instead?

2. 3x the same cd 
cd $GOPATH/src/github.com/IBM/ibm-spectrum-scale-csi-driver

3. You dont write the full path to spectrum-scale-driver.conf
Set the variable CSI_SCALE_PATH before mentioning spectrum-scale-driver.conf

4. You dont write on which node the CSI should be deployed. As it needs kubectl it would be a worker node.

5. Fix relative path in your create.sh script
[root@worker01 deploy]# ./create.sh 
error: the path "deploy/csi-attacher-rbac.yaml" does not exist

6. Why do I need to encode the admin and password in the spectrum-scale-driver.conf ? Can you encode it automatically in your python script?
Also you should add information how to decode it with base64 (for example: echo guipass | base64) if you cannot encode it with python script.

7. In spectrum-scale-driver.conf I need to set mount path for the filesystem. Cant you determine it ? I specified the fs in conf file already.
- Mount path of the primary filesystem. 
scalehostpath = /mnt/gpfs0

8. Add information on how to determine spectrumscaleplugin in  spectrum-scale-driver.conf.
It can be get from the command below, but this information is missing in the github documentation.
podman images | grep spectrum-scale

Maybe you can discover it in your python script ?

9. Use newer versions for these images as the versions used in the conf file are already over 1 year old:
provisioner = quay.io/k8scsi/csi-provisioner:v1.0.0
attacher =  quay.io/k8scsi/csi-attacher:v1.0.0
driverregistrar = quay.io/k8scsi/csi-node-driver-registrar:v1.0.1

10. Dynamic Provisioning Example
The files are called
podfileset.yaml
pvcfileset.yaml
NOT podfset.yaml pvcfset.yaml as in the documentation

11. In spectrum-scale-driver.conf I had to set if I have Openshift. Cant you determine it ? 
- Specify true if this is an openshift deployment
openshiftdeployment = true

12. For remote cluster, provide a way to install it automatically, without editing yaml files. Also, setting remoteFS/remoteCluster in primary section does not seem to be required as the primary FS must be a local one.

**Comment by smitaraut** [comment]
Have you tested with newer version of attacher and provisioner?

**Comment by przem123** [comment]
> Have you tested with newer version of attacher and provisioner?

Yes, I tried them once; they seemed to work properly but I did not test their full functionality.

**Comment by smitaraut** [comment]
#1 - Addressed by giving pre-req - [https://github.com/IBM/ibm-spectrum-scale-csi-driver/tree/devel#building-the-docker-image](https://github.com/IBM/ibm-spectrum-scale-csi-driver/tree/devel#building-the-docker-image)

#2, #3, #4, #5, #6 are no longer valid as the CSI driver has switched to multi-stage docker build for building of images and operator based install for deployment of the driver. 

#7 - We need to give scaleHostpath in operator configuration. Idea is to be able to give even a subdirectory or a parent directory of the filesystem mount point here depending on how much of filesystem you want to expose in the container. In 1.0 release only the FS mount point is supported but in future releases there is consideration on supporting subdirectories.

#8 - Driver images are available from quay.io and are given in CR files of the operator- [https://github.com/IBM/ibm-spectrum-scale-csi-operator](https://github.com/IBM/ibm-spectrum-scale-csi-operator)

#9 - Will take this up in next release

#10 - no more valid. Please refer to IBM knowledge center for instructions - [https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_using.html](https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_using.html)

#11 - no longer valid. There are now common install steps for openshift and kubernetes - [https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_install_usingops.html](https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_install_usingops.html)

#12 - Please check IBM knowledge center on remote cluster configuration- [https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_config_csi_remotemount_final.html](https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_config_csi_remotemount_final.html)

Primary FS can also be a remotely mounted FS. Check the demo videos here-

How to dynamically provision a lightweight volume on a remotely mounted filesystem
[https://youtu.be/xcpk6UbM1ps](https://youtu.be/xcpk6UbM1ps)

How to dynamically provision a fileset based volume on a remotely mounted filesystem
[https://youtu.be/jFKwUi6PXGI](https://youtu.be/jFKwUi6PXGI)

How to configure remotely mounted Spectrum Scale filesystem as a primary filesystem for persistent storage
[https://youtu.be/wKodQwugXWk](https://youtu.be/wKodQwugXWk)

**Comment by smitaraut** [comment]
Only point 9 seems to be a valid request at this time, opened a separate issue for the same- https://github.com/IBM/ibm-spectrum-scale-csi-operator/issues/113

Closing this issue as other points have been answered.
