### ISSUE TITLE
deploy/spectrum-scale-secret.json missing in devel branch

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi-driver#55]
According to the documentation in devel branch, for remote cluster I need to adjust `deploy/spectrum-scale-secret.json`. I dont have it in this branch. I have only `deploy/spectrum-scale-secret.yaml`. 

Can you describe how to adjust the yaml file ?

**Comment by smitaraut** [comment]
Please refer to the IBM knowledge center for CSI driver documentation.

Remote cluster instructions-
[https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_config_csi_remotemount_final.html](https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_config_csi_remotemount_final.html)

Secret for every cluster can be created using the manifest given at-
[https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_config_csi_secret.html](https://www.ibm.com/support/knowledgecenter/STXKQY_5.0.4/com.ibm.spectrum.scale.csi.v5r04.doc/bl1csi_config_csi_secret.html)

**Comment by smitaraut** [comment]
Closing this issue as the secret yaml file is not required to be in github, sample is given in knowledge center doc
